export const taskParameters = {
  // params for route core-tasks/vocab
  // This is what's coming back from `getTask`
  swr: {
    task: {
      publicName: "ROAR - Word",
      image:
        "https://raw.githubusercontent.com/yeatmanlab/roar-assets/main/roar-apps/word-no-lion.png",
      description:
        "Words will flash quickly on the screen. Decide if they are real or made up.",
      lastUpdated: {
        seconds: 1727457612,
        nanoseconds: 676000000,
      },
      name: "ROAR - Word",
      id: "swr",
      studentFacingName: "Word",
      technicalName: "Single Word Recognition (SWR)",
      tutorialVideo:
        "https://storage.googleapis.com/roar-swr/en/shared/ROAR-SWR%20instructional%20video.mp4",
      gameConfig: {
        recruitment: "pilot",
        totalTrialsPractice: 5,
        nRandom: 5,
        addNoResponse: false,
        countSlowPractice: 2,
        skipInstructions: true,
        consent: true,
      },
      registered: true,
    },
    variant: {
      lastUpdated: {
        seconds: 1726698728,
        nanoseconds: 612000000,
      },
      registered: true,
      name: "word-school-shortAdaptive-nostory",
      params: {
        audioFeedbackOption: "binary",
        numAdaptive: 84,
        storyOption: "grade-based",
        addNoResponse: false,
        numValidated: 84,
        numNew: 0,
        userMode: "shortAdaptive",
        recruitment: "school",
        consent: true,
        skipInstructions: true,
      },
      id: "1KZ9rzyX62NIZevN8LqK",
    },
  },
  vocab: {
    task: {
      name: "ROAR - Picture Vocabulary",
      image:
        "https://raw.githubusercontent.com/yeatmanlab/roar-assets/main/roar-apps/picture-vocab-no-lion.png",
      studentFacingName: "Picture Vocab",
      id: "vocab",
      description: "Listen to the words and choose the right picture",
      image:
        "https://storage.googleapis.com/road-dashboard/shared/vocab-logo.png",
      name: "Vocabulary",
    },
    variant: {
      description: "a variant of vocab",
      age: null,
      buttonLayout: "default",
      corpus: "vocab-item-bank",
      keyHelpers: false,
      language: "en",
      maxIncorrect: 3,
      maxTime: 100,
      numOfPracticeTrials: 2,
      numOfTrials: 300,
      sequentialPractice: true,
      sequentialStimulus: true,
      skipInstructions: true,
      stimulusBlocks: 3,
      stormItemId: false,
      taskName: "vocab",
    },
  },
  "egma-math": {
    task: {
      description: "Solve the math problems",
      name: "Math Game",
      image:
        "https://storage.googleapis.com/road-dashboard/shared/math-logo.png",
      studentFacingName: "Math Game",
    },
    variant: {
      age: null,
      buttonLayout: "default",
      corpus: "math-item-bank",
      keyHelpers: false,
      language: "en",
      maxIncorrect: 3,
      maxTime: 100,
      numOfPracticeTrials: 2,
      numOfTrials: 300,
      sequentialPractice: true,
      sequentialStimulus: true,
      skipInstructions: true,
      stimulusBlocks: 3,
      stormItemId: false,
      taskName: "egma-math",
    },
  },
  intro: {
    task: {
      description: "Learn how to play the games",
      image:
        "https://storage.googleapis.com/road-dashboard/shared/intro-logo.png",
      name: "Instructions",
    },
    variant: {
      age: null,
      buttonLayout: "default",
      corpus: "null",
      keyHelpers: false,
      language: "en",
      maxIncorrect: 3,
      maxTime: 100,
      numOfPracticeTrials: 2,
      numberOfTrials: 300,
      sequentialPractice: true,
      sequentialStimulus: true,
      skipInstructions: true,
      stimulusBlocks: 3,
      stormItemId: false,
      description: "a variant of intro",
    },
  },
  "hearts-and-flowers": {
    task: {
      description: "Choose the correct side for the hearts and flowers.",
      image:
        "https://storage.googleapis.com/road-dashboard/shared/hearts-and-flowers-logo.png",
      name: "Hearts and Flowers",
    },
    variant: {
      age: null,
      buttonLayout: "default",
      corpus: "null",
      keyHelpers: false,
      language: "en",
      maxIncorrect: 3,
      maxTime: 100,
      numOfPracticeTrials: 2,
      numberOfTrials: 300,
      sequentialPractice: true,
      sequentialStimulus: true,
      skipInstructions: true,
      stimulusBlocks: 3,
      stormItemId: false,
      description: "hearts and flowers",
    },
  },
  "same-different-selection": {
    task: {
      description: "Find things that are the same about the shapes.",
      image:
        "https://storage.googleapis.com/road-dashboard/shared/same-different-selection-logo.png",
      name: "Shapes Game",
    },
    variant: {
      age: null,
      buttonLayout: "default",
      corpus: "null",
      keyHelpers: false,
      language: "en",
      maxIncorrect: 3,
      maxTime: 100,
      numOfPracticeTrials: 2,
      numberOfTrials: 300,
      sequentialPractice: true,
      sequentialStimulus: true,
      skipInstructions: true,
      stimulusBlocks: 3,
      stormItemId: false,
      taskName: "hearts-and-flowers",
    },
  },
  "memory-game": {
    task: {
      description: "Play the memory game.",
      image:
        "https://storage.googleapis.com/road-dashboard/shared/memory-game-logo.png",
      name: "Memory Game",
    },
    variant: {
      age: null,
      buttonLayout: "default",
      corpus: "null",
      keyHelpers: false,
      language: "en",
      maxIncorrect: 3,
      maxTime: 100,
      numOfPracticeTrials: 2,
      numberOfTrials: 300,
      sequentialPractice: true,
      sequentialStimulus: true,
      skipInstructions: true,
      stimulusBlocks: 3,
      stormItemId: false,
      taskName: "memory-game",
    },
  },
  "matrix-reasoning": {
    task: {
      description: "Find the missing piece to complete the puzzle.",
      image:
        "https://storage.googleapis.com/road-dashboard/shared/matrix-reasoning-logo.png",
      name: "Puzzle Game",
    },
    variant: {
      age: null,
      buttonLayout: "default",
      corpus: "null",
      keyHelpers: false,
      language: "en",
      maxIncorrect: 3,
      maxTime: 100,
      numOfPracticeTrials: 2,
      numberOfTrials: 300,
      sequentialPractice: true,
      sequentialStimulus: true,
      skipInstructions: true,
      stimulusBlocks: 3,
      stormItemId: false,
      taskName: "matrix-game",
    },
  },
  "mental-reasoning": {
    task: {
      description: "Find the missing piece to complete the puzzle.",
      image:
        "https://storage.googleapis.com/road-dashboard/shared/matrix-reasoning-logo.png",
      name: "Puzzle Game",
    },
    variant: {
      age: null,
      buttonLayout: "default",
      corpus: "null",
      keyHelpers: false,
      language: "en",
      maxIncorrect: 3,
      maxTime: 100,
      numOfPracticeTrials: 2,
      numberOfTrials: 300,
      sequentialPractice: true,
      sequentialStimulus: true,
      skipInstructions: true,
      stimulusBlocks: 3,
      stormItemId: false,
      taskName: "mental-reasoning",
    },
  },
  trog: {
    task: {
      description: "Listen to the phrases and choose the right picture.",
      image:
        "https://storage.googleapis.com/road-dashboard/shared/trog-logo.png",

      name: "Words and Pictures Game",
    },
    variant: {
      age: null,
      buttonLayout: "default",
      corpus: "null",
      keyHelpers: false,
      language: "en",
      maxIncorrect: 3,
      maxTime: 100,
      numOfPracticeTrials: 2,
      numberOfTrials: 300,
      sequentialPractice: true,
      sequentialStimulus: true,
      skipInstructions: true,
      stimulusBlocks: 3,
      stormItemId: false,
      taskName: "trog",
    },
  },
  pa: {
    task: {
      description: "Identify the sounds in the words",
      image:
        "https://storage.googleapis.com/road-dashboard/shared/trog-logo.png",
      name: "Pa",
    },
    variant: {
      consent: false,
      numTestItems: null,
      skipInstructions: true,
      userMode: "fixed",
    },
  },
  sre: {
    task: {
      description:
        "Read the sentences as quickly as you can and decide if they are true or false.",
      image:
        "https://raw.githubusercontent.com/yeatmanlab/roar-assets/main/roar-apps/sentence-no-lion.png",
      name: "Sre",
    },
    variant: {
      consent: true,
      recruitment: null,
      storyOption: null,
      skipInstructions: true,
      timerLength: 180000,
      userMode: null,
    },
  },
  "theory-of-mind": {
    task: {
      description: "Listen to the stories and answer the questions.",
      image:
        "https://storage.googleapis.com/road-dashboard/shared/theory-of-mind-logo.png",
      name: "Theory of Mind",
    },
    variant: {
      age: null,
      buttonLayout: "default",
      corpus: "theory-of-mind-item-bank",
      keyHelpers: false,
      language: "en",
      maxIncorrect: 3,
      maxTime: 100,
      numOfPracticeTrials: 2,
      numberOfTrials: 300,
      sequentialPractice: true,
      sequentialStimulus: true,
      skipInstructions: true,
      stimulusBlocks: 3,
      stormItemId: false,
      taskName: "theory-of-mind",
    },
  },
};
