<template>
  <div class="">
    <Navbar />
    <div class="page-wrapper flex flex-col gap-3">
      <div class="mb-3">
        <div class="text-3xl font-bold">Player Launcher</div>
        <div class="text-sm text-gray-600 font-light">
          Launch a player to play a game with a custom username or an
          auto-generated one
        </div>
      </div>
      <div
        class="flex flex-col gap-2 align-center justify-center p-5 bg-stone-100 rounded"
      >
        <div class="flex flex-col">
          <div class="font-bold text-xl mb-5">Custom Username</div>
          <div class="text-sm">
            Please input a custom username for the player.
          </div>
        </div>
        <div class="flex flex-col flex-wrap gap-5 bg-stone-200 w-auto p-3">
          <div class="flex gap-3 items-center">
            <div class="text-sm font-bold">Username:</div>
            <input
              onUpdate="updateUser"
              placeholder="username"
              class="px-2 rounded"
              v-model="customUserName"
            />
            <button
              class="bg-red-900 rouded text-white px-2 rounded"
              :onClick="launchCustomUser"
            >
              Launch
            </button>
          </div>
          <div class="flex flex-row gap-3">
            <div class="text-sm font-light">
              Additional notes for user (optional)
            </div>
            <input />
          </div>
        </div>
      </div>
      <div class="font-light flex align-center justify-center text-gray-400">
        ----------- or ----------
      </div>
      <div
        class="flex flex-col gap-2 align-center justify-center p-5 rounded bg-stone-100"
      >
        <div class="flex flex-col">
          <div class="font-bold text-xl mb-5">Auto Generated Username</div>
          <div class="text-sm">Runs will be stored under this username</div>
        </div>
        <!-- <div class="flex flex-wrap gap-3"> -->
        <div class="flex flex-col flex-wrap gap-3 bg-stone-200 w-auto p-3">
          <div class="flex gap-3 items-center">
            <div class="font-bold text-sm">Username:</div>
            <div class="font-bold border">
              {{ autoGeneratedUsername }}
            </div>
            <button
              class="bg-red-900 rounded text-white px-2"
              :onClick="launchAutogeneratedUser"
            >
              Launch
            </button>
          </div>
          <div class="flex flex-row gap-3">
            <div class="text-sm font-light">
              Additional notes for user (optional)
            </div>
            <input />
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from "vue";
import Navbar from "@/components/Navbar.vue";
const autoGeneratedUsername = ref("teak" + Math.floor(Math.random() * 10000));
const customUserName = ref("");

const launchCustomUser = () => {
  console.log("launching custom user", customUserName.value);
  window.location.href = "/play/" + customUserName.value;
};

const launchAutogeneratedUser = () => {
  console.log("launching autogenerated user");
  console.log(autoGeneratedUsername.value);
  window.location.href = "/play/" + autoGeneratedUsername.value;
};

const updateCustomUser = (event) => {
  console.log("username", event.target.value);
  customUserName.value = event.target.value;
};
</script>
