
<template>
  <div class="flex flex-col gap-3">
<div class="text-3xl font-bold">player launcher </div>
<div class="text-sm text-gray-600 ">
  <div class="font-light">
    Launch a player to play a game with a custom username or an auto-generated one
  </div>
</div>
<div class="flex flex-col gap-2 align-center justify-center p-5 bg-stone-100 rounded">
  <div class="font-bold">
     launch a participant with a custom username
  </div>
  <div class="flex flex-wrap gap-3">
<input onUpdate="updateUser" placeholder="username">
</input>
<button class="bg-red-900 rounded text-white">
  launch 
</button>
  </div>
</div>
<div class="font-light flex align-center justify-center text-gray-400">

 -----------  or -----------
</div>
  <div class="flex flex-col gap-2 align-center justify-center p-5 rounded bg-stone-100">
<div class="font-bold">
  launch a player with an auto generated username
</div>
<div class="flex flex-wrap gap-3">

  <div>
    {{ autoGeneratedUsername}}
  </div>

<button class="bg-red-900 rounded text-white">
  launch
</button>
</div>
</div>

</div>
</template>
    


<script setup>
import { ref } from "vue";
const autoGeneratedUsername = ref("teak" + Math.floor(Math.random() * 10000));

const updateUser = (event) => {
  console.log(event.target.value);
  userName.value = event.target.value;
};
const userName = ref("");

</script>